export  const franksList = ([
    "scorbunny", "eternatus", "barraskewda", "grimmsnarl", 
    "sylveon", "falinks", "haxorus", "growlithe", 
    "grapploct", "gengar", "magikarp", "snorlax", "onix", "gyarados",
    "steelix", "lapras", "cloyster", "butterfree", "machoke", "goldeen", "metapod", 
    "seismitoad", "cinderace", "helioptile", "sudowoodo", "thievul", "rookidee", 
    "gossifleur",  "purrloin", "zigzagoon", "raboot", "blipbug", "dottler",
    "orbeetle", "caterpie", "grubbin", "vikavolt", "hoothoot", "corviknight",
    "skwovet", "greedent", "pidove", "tranquill", "nickit", "obstagoon", "seedot",
    "nuzleaf", "shiftry", "chewtle", "drednaw", "liepard", "yamper", "bunnelby", 
    "diggersby", "minccino", "oddish", "gloom","wingull", "pelipper","galvantula",
    "electrike", "vulpix", "delibird", "snorunt", "mudbray","dwebble", "golurk", "stufful",
    "snover", "wooper", "corphish", "ninjask", "tyrogue", "pancham", "bronzor", 
    "stunky", "tympole", "palpitoad", "dusknoir", "seaking", "octillery", "wishiwashi-solo", 
    "wishiwashi-school", "pyukumuku", "sizzlipede", "rolycoly", "coalossal", "roggenrola",
    "timburr", "gurdurr", "woobat", "arrokuda", "meowth", "perrserker", "cutiefly",
    "pumpkaboo-average", "espurr", "swirlix", "chinchou", "lanturn", "scraggy",
    "stunfisk", "whiscash", "shellos", "barbaracle", "hattrem", "hatterene", "sawk",
    "bonsly", "rhyhorn", "gothitelle", "cubchoo", "rufflet", "skorupi", "litwick", "sneasel",
    "sigilyph", "torkoal", "sandaconda", "hawlucha", "flygon", "axew", "fraxure", "yamask",
    "phantump", "togedemaru", "snom", "mantine", "wailmer", "bergmite", "toxel", "beartic",
    "copperajah", "ditto", "frillish", "gastrodon", "glalie", "inkay", "jolteon", "kingler",
    "klang", "ninetales", "noivern", "wobbuffet", "pikachu", "eevee", "avalugg", "glaceon", 
    "zacian", "shuckle", "gardevoir", "drakloak", "fuecoco", "lechonk", "tarountula", "hoppip",
    "fletchling", "pawmi", "yungoos", "scatterbug", "azurill", "buizel", "wooper", "psyduck",
    "ralts", "drowzee", "gastly", "fidough", "wingull", "wiglett", "flamigo", "crocalor", "charcadet",
    "stantler", "shinx", "skiddo", "sunkern", "surskit"
    

  ])